language: node_js
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: fWVzWDlen8tpkheJchQ9hZOeBvfd5fuADNS92psFwtk3QMYlnW4zuQPeCUs7CJyneUCnM0Dgcgc4wri6O/zIG0TptOcAXOTDTciaSCQegz3RznAxidKQH4LqkuX07GAWN6PhQHYuTx8QecGy2+LlxpR7mscoitLE0ENcF4/n5PzoGWYOhiy9RgCZoo7M9aJFepjcc0SUcpko9VHYHetWB2PCLPVZ5h0FD/1QxDJl3gD+O504p+L9WygYW1aQfRq6oVFf3E3YVMIOYJ+4V/Xr0q2AW5cnxvEaQ7Dlxiz0tuIG543RgwR6c49o48ncVyOmwvjNsl4xcXO2uzyvSduZG1tVofqak01to8vA/QdT+iN+pyqAKk50F9NjPZ3KWsfiA1xXDK1kHEp6zvHRD9Tm2ciS02wfcPaPNvEo8MRIDjGjdzuND9rwu58b3Wmt+vlkKKA10oB3kItRP0uhLUANEpplLbOnuyoMgonw6PYgaHWayZJ8eNsRLlYfCEl2pjTvMJfFjQXBg1GqlyHtPHrOiI9mNA6pjuuE9R5Zk9bWsZde0XBrbW3v257TMeycnrBkMNuJciCaax7nIwJbnGkMqx+ar4OB8H9VbC4b1gz5fwqpwvlP8UUyobXrwjY4/aLktcVyFF5FnfYRTBrZPjPbEV7N5vEs6wIC5er4K/P9z2I=
  app: desolate-springs-35710
  on:
    repo: kltan0301/apiServer
